version: "3"
services:
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8080:80"
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mysql:8.0.27
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
    # ホスト側のポート:コンテナのポート
    ports:
      - '3307:3306'
  wordpress:
    image: wordpress:latest
    volumes:
      - ./html:/var/www/html
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db-user
      WORDPRESS_DB_PASSWORD: db-pass
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data:
  wp_data:
